name: CI/CD Pipeline

on:
  push:
    branches: [ feature-CI/CD ]

permissions:
  contents: write

jobs:
  build-zip-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compress
        run: |
          echo "Workspace:"
          ls -la
          set -euo pipefail
          
          STAGE="uStepperSTM32Hardware"
          rm -rf "$STAGE"
          mkdir -p "$STAGE"
          
          cp -a cores libraries system variants tools "$STAGE/"
          cp -a boards.txt keywords.txt platform.txt programmers.txt "$STAGE/"
          
          tar -cjf uStepperSTM32Hardware.tar.bz2 "$STAGE"
      - name: Upload tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: uStepperSTM32Hardware-tar-bundle
          path: uStepperSTM32Hardware.tar.bz2
          
  build:
    needs: [ build-zip-bundle]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download archive artifact
      uses: actions/download-artifact@v4
      with:
        name: uStepperSTM32Hardware-tar-bundle
        path: .

    - name: List tar contents
      run: |
        tar -tjf uStepperSTM32Hardware.tar.bz2
