name: CI/CD Pipeline

on:
  push:
    branches: [ feature-CI/CD ]

permissions:
  contents: write

jobs:
  build-zip-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compress
        run: |
          cd ..
          echo "Workspace:"
          ls -la
          echo "Repo root:"
          ls -la uStepperSTM32Hardware
          echo "Find candidates:"
          find uStepperSTM32Hardware -maxdepth 2 -type d -name 'board*' -o -name 'boards*' | sed 's|^|  - |'
          tar -cjf uStepperSTM32Hardware.tar.bz2 \
            uStepperSTM32Hardware/cores \
            uStepperSTM32Hardware/libraries \
            uStepperSTM32Hardware/boards
      - name: Upload tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: uStepperSTM32Hardware-tar-bundle
          path: uStepperSTM32Hardware.tar.bz2
          
  build:
    needs: [ build-zip-bundle]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download archive artifact
      uses: actions/download-artifact@v4
      with:
        name: uStepperSTM32Hardware-tar-bundle
        path: .

    - name: List tar contents
      run: |
        tar -tjf uStepperSTM32Hardware.tar.bz2
